// Usage (Pani Entry) data access. Rows are returned exactly as the database sends them, so they stay
// assignable to the ledger engine's LedgerUsage input type. total_minutes is generated by the
// database and is never sent.
import { parseInstantMs, validateUsageInput } from '@/lib/ledger';
import { supabase } from '@/lib/supabase';
import type { Database } from '@/types/database';
import { nowIso } from './clock';
import { DataError } from './errors';
import { fetchAllRows } from './paging';
import { oneRow } from './rows';
import type { UsageInput } from './usageRules';

export type UsageRow = Database['public']['Tables']['usage_entries']['Row'];
type UsageUpdate = Database['public']['Tables']['usage_entries']['Update'];

function checked(input: UsageInput): UsageInput {
  const codes = validateUsageInput(input);
  if (codes.length > 0) throw new DataError('constraint', 'client_validation', codes.join(','));
  return input;
}

/** Every usage row (live and deleted), read page by page in id order. */
export function listUsage(): Promise<UsageRow[]> {
  return fetchAllRows<UsageRow>((from, to) => supabase.from('usage_entries').select('*').order('id').range(from, to));
}

export async function createUsage(input: UsageInput): Promise<UsageRow> {
  const { farmer_id, used_at, hours, minutes, rate_paise } = checked(input);
  return oneRow(
    await supabase.from('usage_entries').insert({ farmer_id, used_at, hours, minutes, rate_paise }).select().single(),
  );
}

async function updateLiveUsage(id: string, patch: UsageUpdate): Promise<UsageRow> {
  return oneRow(await supabase.from('usage_entries').update(patch).eq('id', id).is('deleted_at', null).select().maybeSingle());
}

/**
 * Saves an edited, non-deleted entry, sending only the columns that changed (used_at is compared as
 * an instant, so "+00:00" from the database equals the same moment written with "+05:30").
 * With nothing changed it makes no request and returns `current`.
 */
export async function updateUsage(current: UsageRow, input: UsageInput): Promise<UsageRow> {
  const next = checked(input);
  const patch: { farmer_id?: string; used_at?: string; hours?: number; minutes?: number; rate_paise?: number } = {};
  if (next.farmer_id !== current.farmer_id) patch.farmer_id = next.farmer_id;
  if (parseInstantMs(next.used_at) !== parseInstantMs(current.used_at)) patch.used_at = next.used_at;
  if (next.hours !== current.hours) patch.hours = next.hours;
  if (next.minutes !== current.minutes) patch.minutes = next.minutes;
  if (next.rate_paise !== current.rate_paise) patch.rate_paise = next.rate_paise;
  if (Object.keys(patch).length === 0) return current;
  return updateLiveUsage(current.id, patch);
}

/** Soft delete: sets deleted_at (the trigger sets deleted_by). An entry that is already deleted gives not_found. */
export function softDeleteUsage(id: string): Promise<UsageRow> {
  return updateLiveUsage(id, { deleted_at: nowIso() });
}

/** Restore: deleted_at back to null (the trigger clears deleted_by). An entry that is not deleted gives not_found. */
export async function restoreUsage(id: string): Promise<UsageRow> {
  return oneRow(
    await supabase.from('usage_entries').update({ deleted_at: null }).eq('id', id).not('deleted_at', 'is', null).select().maybeSingle(),
  );
}
