// Pure Pani Entry (usage) rules: no I/O. Money, rounding and IST math come from the ledger engine.
import {
  LedgerInputError,
  entryAmountPaise,
  findDuplicateUsage,
  istDateKey,
  istTimeKey,
  istWallClockToIso,
  paiseToDecimalString,
  parseInstantMs,
  parseRupeesToPaise,
  validateUsageInput,
} from '@/lib/ledger';
import type { ValidationCode } from '@/lib/ledger';
import { dayOrNull, monthOf, monthsNewestFirst, sortNewestFirst } from './timeline';

/** The engine codes that apply to a usage entry (the payment-only amount codes do not). */
export type UsageValidationCode = Exclude<
  ValidationCode,
  'amount_required' | 'amount_not_integer' | 'amount_negative' | 'amount_not_positive'
>;

/** Every code the usage form can show: the engine usage codes plus the rate text that cannot be read. */
export type UsageFormCode = UsageValidationCode | 'rate_invalid';

/** The form exactly as typed (strings). The rate is rupees per hour. */
export interface UsageForm {
  readonly farmerId: string;
  /** IST date "YYYY-MM-DD". */
  readonly date: string;
  /** IST time "HH:mm". */
  readonly time: string;
  readonly hours: string;
  readonly minutes: string;
  readonly rate: string;
}

/** Values as written to the database (`total_minutes` is generated by the database and never sent). */
export interface UsageInput {
  readonly farmer_id: string;
  readonly used_at: string;
  readonly hours: number;
  readonly minutes: number;
  readonly rate_paise: number;
}

/** The usage columns these rules read. DB rows are assignable to it. */
export interface UsageRowLike {
  readonly id: string;
  readonly farmer_id: string;
  readonly used_at: string;
  readonly hours: number;
  readonly minutes: number;
  readonly total_minutes: number | null;
  readonly rate_paise: number;
  readonly created_at: string;
  readonly deleted_at: string | null;
}

export interface IstMoment {
  readonly dateKey: string;
  readonly timeKey: string;
  readonly monthKey: string;
}

/** The default rate of a new entry: 100 rupees per hour (L2). */
export const DEFAULT_RATE_TEXT = '100';

/** A blank form for a new entry, dated at `now` (IST), 0 hours 0 minutes, default rate. */
export function newUsageForm(now: IstMoment, farmerId = ''): UsageForm {
  return { farmerId, date: now.dateKey, time: now.timeKey, hours: '0', minutes: '0', rate: DEFAULT_RATE_TEXT };
}

/** The form prefilled from a stored entry (IST date and time, rate in rupees). */
export function usageFormFromRow(row: UsageRowLike): UsageForm {
  const ms = parseInstantMs(row.used_at);
  return {
    farmerId: row.farmer_id,
    date: istDateKey(ms),
    time: istTimeKey(ms),
    hours: String(row.hours),
    minutes: String(row.minutes),
    rate: paiseToDecimalString(row.rate_paise),
  };
}

const DIGITS = /^[0-9]+$/;

/** '' -> null (required), digits -> number, anything else -> NaN (not an integer). */
function wholeNumber(text: string): number | null {
  if (text === '') return null;
  return DIGITS.test(text) ? Number(text) : Number.NaN;
}

export type BuildUsageResult =
  | { readonly ok: true; readonly input: UsageInput }
  | { readonly ok: false; readonly codes: UsageFormCode[] };

/**
 * Turns the typed form into database values, or the list of problems. Hours and minutes must be
 * digits only; the rate goes through parseRupeesToPaise; date and time through istWallClockToIso;
 * then the engine's validateUsageInput decides. Never throws.
 */
export function buildUsageInput(form: UsageForm): BuildUsageResult {
  const farmerId = form.farmerId.trim();
  const date = form.date.trim();
  const time = form.time.trim();
  const rateText = form.rate.trim();

  let usedAt = '';
  if (date !== '' && time !== '') usedAt = istWallClockToIso(date, time) ?? 'invalid';

  let ratePaise: number | null = null;
  let rateInvalid = false;
  if (rateText !== '') {
    try {
      ratePaise = parseRupeesToPaise(rateText);
    } catch {
      rateInvalid = true;
      ratePaise = 1; // placeholder so the other checks still run; rate_invalid is reported instead
    }
  }

  const candidate = {
    farmer_id: farmerId,
    used_at: usedAt,
    hours: wholeNumber(form.hours.trim()),
    minutes: wholeNumber(form.minutes.trim()),
    rate_paise: ratePaise,
  };
  let codes: UsageFormCode[] = validateUsageInput(candidate) as UsageValidationCode[];
  if (rateInvalid) codes = [...codes.filter((c) => c !== 'amount_too_large'), 'rate_invalid'];
  if (codes.length > 0) return { ok: false, codes };
  return {
    ok: true,
    input: {
      farmer_id: farmerId,
      used_at: usedAt,
      hours: candidate.hours ?? 0,
      minutes: candidate.minutes ?? 0,
      rate_paise: ratePaise ?? 0,
    },
  };
}

/** The amount of a valid input (as built by buildUsageInput), through the engine's one rounding (D7). */
export function usageInputAmountPaise(input: UsageInput): number {
  return entryAmountPaise(input.hours * 60 + input.minutes, input.rate_paise);
}

/**
 * The amount of a stored entry. A row whose total_minutes is null or differs from hours*60+minutes
 * throws LedgerInputError: it is never fixed silently (K-03).
 */
export function usageAmountPaise(row: Pick<UsageRowLike, 'hours' | 'minutes' | 'total_minutes' | 'rate_paise'>): number {
  if (row.total_minutes === null || row.total_minutes !== row.hours * 60 + row.minutes) {
    throw new LedgerInputError('usage total_minutes is missing or does not match hours and minutes');
  }
  return entryAmountPaise(row.total_minutes, row.rate_paise);
}

export type UsageWarning<T> =
  | { readonly kind: 'duplicate'; readonly matches: T[] }
  | { readonly kind: 'long_duration' }
  | { readonly kind: 'future_date' };

/** An entry whose TOTAL time (hours and minutes) is over this many hours gives a (non-blocking) warning (D25). */
export const LONG_DURATION_HOURS = 24;
const LONG_DURATION_MINUTES = LONG_DURATION_HOURS * 60;

/**
 * Non-blocking warnings for a valid input: same farmer/IST day/hours/minutes (L14), more than 24
 * hours, or an IST date after today. When editing, pass the entry as `original` (and its id as
 * `excludeId`): a warning whose fields did not change is not raised again. Never throws.
 */
export function describeUsageWarnings<T extends UsageRowLike>(
  input: UsageInput,
  existing: readonly T[],
  now: Pick<IstMoment, 'dateKey'>,
  options: { readonly excludeId?: string; readonly original?: UsageRowLike } = {},
): UsageWarning<T>[] {
  const warnings: UsageWarning<T>[] = [];
  const original = options.original;
  const day = dayOrNull(input.used_at);
  const sameDay = original !== undefined && day !== null && dayOrNull(original.used_at) === day;

  const duplicateFieldsUnchanged =
    original !== undefined &&
    sameDay &&
    original.farmer_id === input.farmer_id &&
    original.hours === input.hours &&
    original.minutes === input.minutes;
  if (!duplicateFieldsUnchanged) {
    const matches = findDuplicateUsage({ id: options.excludeId, ...input }, existing);
    if (matches.length > 0) warnings.push({ kind: 'duplicate', matches });
  }

  // Total time over 24 h 00 min warns (24 h 01 min does, exactly 24 h does not).
  const totalMinutes = input.hours * 60 + input.minutes;
  const durationUnchanged = original !== undefined && original.hours * 60 + original.minutes === totalMinutes;
  if (totalMinutes > LONG_DURATION_MINUTES && !durationUnchanged) warnings.push({ kind: 'long_duration' });

  if (day !== null && day > now.dateKey && !sameDay) warnings.push({ kind: 'future_date' });
  return warnings;
}

export interface UsageLists<T> {
  readonly live: T[];
  readonly deleted: T[];
}

/** The ONE soft-delete split for usage: deleted = deleted_at set. Each list newest first. */
export function classifyUsage<T extends UsageRowLike>(rows: readonly T[]): UsageLists<T> {
  return {
    live: sortNewestFirst(rows.filter((r) => r.deleted_at === null), (r) => r.used_at),
    deleted: sortNewestFirst(rows.filter((r) => r.deleted_at !== null), (r) => r.used_at),
  };
}

export interface UsageFilter {
  /** Only this farmer's entries; undefined = every farmer. */
  readonly farmerId?: string;
  /** Only this IST month ("YYYY-MM"); undefined = every month. */
  readonly monthKey?: string;
}

export function filterUsage<T extends UsageRowLike>(rows: readonly T[], filter: UsageFilter): T[] {
  return rows.filter(
    (r) =>
      (filter.farmerId === undefined || r.farmer_id === filter.farmerId) &&
      (filter.monthKey === undefined || monthOf(r.used_at) === filter.monthKey),
  );
}

/** Distinct IST months of the rows plus the current month, newest first. */
export function listUsageMonths(rows: readonly UsageRowLike[], currentMonthKey: string): string[] {
  return monthsNewestFirst(rows.map((r) => monthOf(r.used_at)), currentMonthKey);
}
